### ISSUE TITLE
bookObject

### ISSUE THREAD

**Issue by PovilasKorop** [renatas-php/book-shopas#10]
https://github.com/renatas-php/book-shopas/blob/0a73efdbc2db3d58b69326a1f04becdd23a6b956/app/Http/Controllers/HomeController.php#L36

O kam čia šitas bookObject? Neradau Blade kad būtų panaudotas.

**Comment by renatas-php** [comment]
Naudojau čia
https://github.com/renatas-php/book-shopas/blob/main/resources/views/admin/dashboard.blade.php
Bet iš kontrolerio taip ir neištryniau, nes ta patį book objecta idejau i
provideri su view::composer funkcija, pradžiai galvojau kad pasirašysiu
daugiau funkcijų book modelyje, bet pasirašiau tik count kad skaiciuotu
approved ir neapproved, bet jau žinau kad tokiam apskaičiavimui laravelis
turi savas funkcijas.

**Comment by PovilasKorop** [comment]
Ok cool
